# Generated by Django 5.1.7 on 2025-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100, null=True)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('confirmPass', models.CharField(max_length=50, null=True)),
                ('addresh', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('profilePic', models.ImageField(default='No Profile', upload_to='static\\userProfile')),
            ],
            options={
                'db_table': 'userModel',
            },
        ),
    ]
