# Generated by Django 5.1.7 on 2025-04-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourPlaces',
            fields=[
                ('placeID', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=100, null=True)),
                ('placeLocation', models.CharField(max_length=100, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('placePic', models.ImageField(default='No profile', upload_to='static\\placePic')),
                ('description', models.TextField(max_length=1000, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
