# Generated by Django 5.1.7 on 2025-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tourplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplaces',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
