# Generated by Django 5.1.7 on 2025-04-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tourplaces_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourplaces',
            table='tourPlaces',
        ),
    ]
