# Generated by Django 5.1.7 on 2025-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tourplaces_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='addFlightsModel',
            fields=[
                ('flightId', models.AutoField(primary_key=True, serialize=False)),
                ('From', models.CharField(max_length=100, null=True)),
                ('To', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('ticketPrice', models.CharField(max_length=100, null=True)),
                ('flightName', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'addFlightsModel',
            },
        ),
    ]
