# Generated by Django 5.1.7 on 2025-04-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addflightsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addflightsmodel',
            name='flightPic',
            field=models.ImageField(default='No profile', upload_to='static\\flightPic'),
        ),
    ]
