# Generated by Django 5.1.7 on 2025-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addflightsmodel_flightpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='addHotelsModel',
            fields=[
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('hotelPic', models.ImageField(default='No profile', upload_to='static\\placePic')),
                ('price', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'addHotelsModel',
            },
        ),
    ]
