# Generated by Django 5.1.7 on 2025-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addhotelsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhotelsmodel',
            name='hotelPic',
            field=models.ImageField(default='No profile', upload_to='static\\hotelPic'),
        ),
    ]
