# Generated by Django 5.1.7 on 2025-04-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_addhotelsmodel_hotelpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('carCompany', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('carPic', models.ImageField(default='No profile', upload_to='static\\carPic')),
                ('bookingStatus', models.CharField(default='Available', max_length=50)),
            ],
            options={
                'db_table': 'carModel',
            },
        ),
    ]
