# Generated by Django 5.1.7 on 2025-04-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('hospitalId', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('hospitalPic', models.ImageField(default='No profile', upload_to='static\\hospitalPic')),
            ],
            options={
                'db_table': 'HospitalModel',
            },
        ),
    ]
