# Generated by Django 5.1.7 on 2025-04-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_hospitalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='h_emergency_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
