# Generated by Django 5.1.7 on 2025-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_hospitalmodel_h_emergency_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplaces',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
