# Generated by Django 5.1.7 on 2025-04-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tourplaces_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addflightsmodel',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
