# Generated by Django 5.1.7 on 2025-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_addflightsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhotelsmodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
