# Generated by Django 5.1.7 on 2025-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_addhotelsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='closes',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='open',
            field=models.TimeField(null=True),
        ),
    ]
