# Generated by Django 5.2 on 2025-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_hospitalmodel_closes_hospitalmodel_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplaces',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tourplaces',
            name='places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tourplaces',
            name='restaurants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
