# Generated by Django 5.2 on 2025-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tourplaces_image_tourplaces_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('payment_for', models.CharField(max_length=50, null=True)),
                ('paymenter_name', models.CharField(max_length=50, null=True)),
                ('paymenter_mail', models.EmailField(max_length=254, null=True)),
                ('card_no', models.CharField(max_length=100, null=True)),
                ('timeStamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
