# Generated by Django 5.2 on 2025-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_paymentmodel_hospitalmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='Booking_ID',
            field=models.IntegerField(null=True),
        ),
    ]
