# Generated by Django 5.2 on 2025-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_paymentmodel_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='paid_amount',
            field=models.IntegerField(null=True),
        ),
    ]
