# Generated by Django 5.2 on 2025-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_paymentmodel_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
