# Generated by Django 5.2 on 2025-04-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_paymentmodel_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentmodel',
            table='PaymentModel',
        ),
    ]
