# Generated by Django 5.2 on 2025-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_paymentmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhotelsmodel',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
