# Generated by Django 5.2 on 2025-05-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_addhotelsmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergencyMail',
            fields=[
                ('emergencyMailID', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalMail', models.EmailField(max_length=254, null=True)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'emergencyMail',
            },
        ),
    ]
