# Generated by Django 5.2 on 2025-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_emergencymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplaces',
            name='placeType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
