from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('userRegistration/', userRegistration, name='userRegistration'),
    path('login/', login, name='login'),
    path('home/', home, name='home'),
    path('adminLogin/', adminLogin, name='adminLogin'),
    path('about/', about, name='about'),
    path('logout/', logout, name='logout'),
    path('addPlaces/', addPlaces, name='addPlaces'),
    path('appPlans/', appPlans, name='appPlans'),
    path('addHotels/', addHotels, name='addHotels'),
    path('addCars/', addCars, name='addCars'),
    path('addHospitals/', addHospitals, name='addHospitals'),
    path('viewUsers/', viewUsers, name='viewUsers'),
    path('removeUser/<int:id>/', removeUser, name='removeUser'),
    path('userProfile/', userProfile, name='userProfile'),
    path('viewPlaces/', viewPlaces, name='viewPlaces'),
    path('viewFlights/', viewFlights, name='viewFlights'),
    path('view_and_book_cars/', view_and_book_cars, name='view_and_book_cars'),
    path('viewHotels/', viewHotels, name='viewHotels'),
    path('viewHospitals/', viewHospitals, name='viewHospitals'),
    path('destinations/', destinations, name='destinations'),
    path('destdetails/<int:placeID>', destdetails, name='destdetails'),
    path('addsubplaces/<int:placeID>', addsubplaces, name='addsubplaces'),
    path('addfoods/<int:placeID>', addfoods, name='addfoods'),
    path('deleteplace/<int:id>/<int:jid>/',deleteplace,name='deleteplace'),
    path('deletefoods/<int:id>/<int:jid>/',deletefoods,name='deletefoods'),
    path('placesingledest/<int:placeID>/<int:jid>', placesingledest, name='placesingledest'),
    path('foodsingledest/<int:placeID>/<int:jid>/', foodsingledest, name='foodsingledest'),
    path('payment/<int:id>/', payment, name='payment'),
    path('chat/', chatbot_page, name='chatbot_page'),
    path('chatbot/', chatbot_response, name='chatbot_response'),
    path('RemoveFlight/<int:id>/', RemoveFlight, name='RemoveFlight'),
    path('removeVehicles/<int:id>/', removeVehicles, name='removeVehicles'),
    path('removeHospitals/<int:id>/', removeHospitals, name='removeHospitals'),
    path('viewEmargencyMails/<str:hospital_mail>/', viewEmargencyMails, name='viewEmargencyMails'),
    path('viewAllEmergencyMails/', viewAllEmergencyMails, name='viewAllEmergencyMails'),
    path('deleteTourPlaces/<int:id>/', deleteTourPlaces, name='deleteTourPlaces')
]